version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 2
      semver-major-days: 7
    open-pull-requests-limit: 10
